name: rarolabs
description: A new Flutter project with MVVM architecture.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & Dependency Injection
  provider: ^6.0.5
  get_it: ^7.6.0

  # Networking & Data
  http: ^1.1.0
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3

  # Utils
  faker: ^2.2.0
  connectivity_plus: ^4.0.2

  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.5.0
  test: ^1.21.0

flutter:
  uses-material-design: true
